//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiColegios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int actividadId { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaInicial { get; set; }
        public Nullable<System.DateTime> fechafinal { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> fundacionId { get; set; }
    
        public virtual Fundacion Fundacion { get; set; }
    }
}
