//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiColegios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acudiente
    {
        public int acudienteId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string direccionTrabajo { get; set; }
        public string empresa { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
