//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiColegios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psicologo
    {
        public int psicologoId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string especialidad { get; set; }
    }
}
