//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiColegios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Acudiente = new HashSet<Acudiente>();
            this.Estudiante = new HashSet<Estudiante>();
            this.Respuesta_Estudiante = new HashSet<Respuesta_Estudiante>();
        }
    
        public int usuarioId { get; set; }
        public string identificacion { get; set; }
        public string tipoDocumento { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<decimal> celular { get; set; }
        public string genero { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> institucionId { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> rolId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acudiente> Acudiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiante> Estudiante { get; set; }
        public virtual Institucion Institucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta_Estudiante> Respuesta_Estudiante { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
